from abc import ABC, abstractmethod
from typing import Any, Dict


class BaseStore(ABC):
    @abstractmethod
    def get(self, key: str, default: Any = None) -> Any: ...
    @abstractmethod
    def set(self, key: str, value: Any) -> None: ...
    @abstractmethod
    def delete(self, key: str) -> None: ...
    @abstractmethod
    def exists(self, key: str) -> bool: ...
    @abstractmethod
    def all(self) -> Dict[str, Any]: ...
    @abstractmethod
    def flush(self) -> None: ...
